<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0</TargetFrameworks>
    <TargetFramework></TargetFramework>
    <OutputType>Exe</OutputType>
    <LangVersion>latest</LangVersion>
    <SignAssembly>false</SignAssembly>
    <IsPackable>true</IsPackable>
    <Description>Darc CLI</Description>
    <PackageTags>Arcade Darc CLI Dependency Flow</PackageTags>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>darc</ToolCommandName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Maestro\Maestro.Common\Maestro.Common.csproj" />
    <ProjectReference Include="..\DarcLib\Microsoft.DotNet.DarcLib.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="CommandLineParser" />
    <PackageReference Include="LibGit2Sharp" />
    <PackageReference Include="Microsoft.Extensions.Http" VersionOverride="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" VersionOverride="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" VersionOverride="8.0.0" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>
</Project>
